services:
  postgres-export:
    extends:
      file: backup/docker-compose.yml
      service: postgres-export
    networks:
      backend:
    depends_on:
      db:
        condition: service_healthy

  backend:
    networks:
      prodenv-shared-internal:
        aliases:
          - ${COMPOSE_PROJECT_NAME}-backend

  frontend:
    networks:
      prodenv-shared-internal:
        aliases:
          - ${COMPOSE_PROJECT_NAME}-frontend

networks:
  prodenv-shared-internal:
    external: true

  backend:

volumes:
  backup-staging:
    external: true
    name: prodenv-backup-staging
