services:
  db:
    extends:
      file: db/docker-compose.yml
      service: db
    networks:
      backend:

  flyway:
    extends:
      file: flyway/docker-compose.yml
      service: flyway
    networks:
      backend:
    depends_on:
      db:
        condition: service_healthy

  backend:
    extends:
      file: backend/docker-compose.yml
      service: backend
    networks:
      backend:
    depends_on:
      flyway:
        condition: service_completed_successfully

  frontend:
    extends:
      file: frontend/docker-compose.yml
      service: frontend
    networks:
      backend:
    depends_on:
      backend:
        condition: service_healthy

volumes:
  volume-db:
  volume-db-backup:

networks:
  backend:
