services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: fullstack_starter_db
    volumes:
      - volume-db:/var/lib/postgresql/data
    env_file:
      - ../${COMPOSE_ENV_FILE:-.env}
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d fullstack_starter_db'" ]
      interval: 5s
      timeout: 5s
      retries: 100

