session:
  cookieDomain: 127.0.0.1
  cookieName: JSESSIONID-LOCAL

oauth:
  registration:
    redirectUri: http://127.0.0.1:8080/login/oauth2/code/google-fullstack-starter

app:
  csrfCookieName: XSRF-TOKEN-LOCAL
  cookie:
    secure: false
    sameSite: Lax

logging:
  levels:
    org.example.fullstackstarter.web.exception.GlobalExceptionHandler: debug
    DB: info
    Exposed: info
