datasource:
  url: jdbc:postgresql://${POSTGRES_ADDRESS:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:fullstack_starter_db}
  username: ${POSTGRES_APP_USER:d}
  password: ${POSTGRES_APP_PASSWORD:d}
  driverClassName: org.postgresql.Driver

flyway:
  enabled: false
