oauth:
  registration:
    registrationId: google-fullstack-starter
    clientId: ${GOOGLE_CLIENT_ID}
    clientSecret: ${GOOGLE_CLIENT_SECRET}
    redirectUri: ${APP_REDIRECT_URI:}
    scope: openid,profile,email
  provider:
    authorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    tokenUri: https://oauth2.googleapis.com/token
    userInfoUri: https://openidconnect.googleapis.com/v1/userinfo
    jwkSetUri: https://www.googleapis.com/oauth2/v3/certs

app:
  defaultSuccessUrl: ${APP_DEFAULT_SUCCESS_URL}
  loginUrl: ${APP_LOGIN_URL}
